### ISSUE TITLE
pull delimiter=null still has structure

### ISSUE THREAD

**Issue by wfjsw** [tolgee/tolgee-cli#89]
Tolgee CLI 2.0.3 + Tolgee Platform 3.64.8. 
Seems to be a regression of #57 

Config: 
```
$schema: "https://tolgee.io/cli-schema.json"
projectId: 20
delimiter: null
format: JSON_TOLGEE
push: 
  files:
    - path: "./StableDiffusionWebUILauncher/Localizations/Bundled/zh-Hans.json"
      language: "zh-Hans"
      forceMode: OVERRIDE
      convertPlaceholdersToIcu: true
pull:
  path: "./StableDiffusionWebUILauncher/Localizations/Bundled"
  state: 
    - REVIEWED
  emptyDir: false
```

![image](https://github.com/tolgee/tolgee-cli/assets/2220320/fde53d3f-5788-4911-8844-86085de077f7)
